// Import JetBrains Mono from the correct path
import { JetBrains_Mono } from 'next/font/google'; 
// Import localFont for your local fonts
import localFont from 'next/font/local'; 
import './globals.css';

// Configure JetBrains Mono from Google Fonts
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrainsMono',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

// Configure your local Geist Mono font
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff', // Correct path to your font file
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
